image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - export RELEASE=`cat VERSION`
    - docker build --build-arg RELEASE="$RELEASE" -t atefhaloui/serverless .
    - docker tag atefhaloui/serverless:latest atefhaloui/serverless:"$RELEASE"
  script:
    - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    - docker push atefhaloui/serverless:latest;
    - docker push atefhaloui/serverless:"$RELEASE";
  only:
    - tags
  except:
    - schedules
